In [2]:
# Create a 2d array with elements as 4,2,5 in 1st row and 3,7,5 in 2nd row
import numpy as np 
arr = np.array([[4,2,5],[3,7,5]])
print(arr)

[[4 2 5]
 [3 7 5]]

In [5]:
# Print type of arr object
print(type(arr))

<class 'numpy.ndarray'>

In [6]:
# Print array dimensions 
print(arr.ndim)

2

In [7]:
# Print shape of array
print(arr.shape)

(2, 3)

In [8]:
# Print size (total number of elements) of array
print(arr.size)

6

In [9]:
# Print type of elements in array
print(arr.dtype)

int64

In [25]:
# Create a sequence of 10 values in range 0 to 5
import numpy as np
a = np.arange(0,5,0.5)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [11]:
# Reshaping 2*3 array to 3*2 array
arr.reshape(3,2)

array([[4, 2],
       [5, 3],
       [7, 5]])

# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

**Import pandas library**

In [26]:
import pandas as pd

**Read Salaries.csv as a dataframe called sal**

In [27]:
sal = pd.read_csv(r'/content/Salaries.csv')

print(sal.to_string())

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

**Check the head of the DataFrame.**

In [28]:
sal.head

<bound method NDFrame.head of             Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6
...                                                ...           ...
148649                                       Custodian             0
148650                                    Not provided  Not Provided
148651                                    Not provided  Not Provided
148652                                    Not provided  Not Provided
148653                      Counselor, Log Cabin Ranch             0

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43
1          245131.88     137811.38           NaN  538909.28         538909.28
2          106088.18       16452.6           NaN  335279.91         335279.91
3           56120.71      198306.9           NaN  332343.61         332343.61
4             9737.0     182234.59           NaN  326373.19         326373.19
...              ...           ...           ...        ...               ...
148649             0             0             0       0.00              0.00
148650  Not Provided  Not Provided  Not Provided       0.00              0.00
148651  Not Provided  Not Provided  Not Provided       0.00              0.00
148652  Not Provided  Not Provided  Not Provided       0.00              0.00
148653             0       -618.13             0    -618.13           -618.13

        Year  Notes         Agency Status
0       2011    NaN  San Francisco    NaN
1       2011    NaN  San Francisco    NaN
2       2011    NaN  San Francisco    NaN
3       2011    NaN  San Francisco    NaN
4       2011    NaN  San Francisco    NaN
...      ...    ...            ...    ...
148649  2014    NaN  San Francisco     PT
148650  2014    NaN  San Francisco    NaN
148651  2014    NaN  San Francisco    NaN
148652  2014    NaN  San Francisco    NaN
148653  2014    NaN  San Francisco     PT

[148654 rows x 13 columns]>

**Use the .info() method to find out how many entries there are in each field.**

In [29]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB