In [1]:
import numpy as np
import pandas as pd

In [2]:
df1=pd.DataFrame({"customer":['A','B','C','D'],
                  'category':['cat1','cat2','cat3','cat4'],
                  'important':['y','n','y','n'],
                  'sales':[123,45,67,890]})

In [3]:
df1

  customer category important  sales
0        A     cat1         y    123
1        B     cat2         n     45
2        C     cat3         y     67
3        D     cat4         n    890

In [4]:
df2=pd.DataFrame({"customer":['A','B','C','E'],
                  'color':['yellow','pink','blue','green'],
                  'important':['y','n','y','n'],
                  'sales':[123,45,67,908]})

In [5]:
df2

  customer   color important  sales
0        A  yellow         y    123
1        B    pink         n     45
2        C    blue         y     67
3        E   green         n    908

In [6]:
pd.concat([df1,df2], axis=0)

  customer category important  sales   color
0        A     cat1         y    123     NaN
1        B     cat2         n     45     NaN
2        C     cat3         y     67     NaN
3        D     cat4         n    890     NaN
0        A      NaN         y    123  yellow
1        B      NaN         n     45    pink
2        C      NaN         y     67    blue
3        E      NaN         n    908   green

In [7]:
pd.concat([df1,df2], axis=1)

  customer category important  sales customer   color important  sales
0        A     cat1         y    123        A  yellow         y    123
1        B     cat2         n     45        B    pink         n     45
2        C     cat3         y     67        C    blue         y     67
3        D     cat4         n    890        E   green         n    908

In [8]:
pd.merge(df1,df2,how='outer',on='customer')

  customer category important_x  sales_x   color important_y  sales_y
0        A     cat1           y    123.0  yellow           y    123.0
1        B     cat2           n     45.0    pink           n     45.0
2        C     cat3           y     67.0    blue           y     67.0
3        D     cat4           n    890.0     NaN         NaN      NaN
4        E      NaN         NaN      NaN   green           n    908.0

In [ ]:
df1

  customer category important  sales
0        A     cat1         y    123
1        B     cat2         n     45
2        C     cat3         y     67
3        D     cat4         n    890

In [ ]:
df2

  customer   color important  sales
0        A  yellow         y    123
1        B    pink         n     45
2        C    blue         y     67
3        E   green         n    908

In [9]:
pd.merge(df1,df2,how='inner',on='important')

  customer_x category important  sales_x customer_y   color  sales_y
0          A     cat1         y      123          A  yellow      123
1          A     cat1         y      123          C    blue       67
2          C     cat3         y       67          A  yellow      123
3          C     cat3         y       67          C    blue       67
4          B     cat2         n       45          B    pink       45
5          B     cat2         n       45          E   green      908
6          D     cat4         n      890          B    pink       45
7          D     cat4         n      890          E   green      908

In [ ]:
pd.merge(df1,df2,how='left',on='customer')

  customer category important_x  sales_x   color important_y  sales_y
0        A     cat1           y      123  yellow           y    123.0
1        B     cat2           n       45    pink           n     45.0
2        C     cat3           y       67    blue           y     67.0
3        D     cat4           n      890     NaN         NaN      NaN

In [10]:
df3=pd.DataFrame({'Q1':[1,2,3],
                  'Q2':[4,5,6]},
                 index=['I0','I1','I2'])

In [ ]:
df3

    Q1  Q2
I0   1   4
I1   2   5
I2   3   6

In [ ]:
df4=pd.DataFrame({'Q3':[7,8,9],
                  'Q4':[10,11,12]},
                 index=['I0','I1','I3'])

In [ ]:
df4

    Q3  Q4
I0   7  10
I1   8  11
I3   9  12

In [ ]:
df3.join(df4,how='inner')

    Q1  Q2  Q3  Q4
I0   1   4   7  10
I1   2   5   8  11

In [ ]:
df1

  customer category important  sales
0        A     cat1         y    123
1        B     cat2         n     45
2        C     cat3         y     67
3        D     cat4         n    890

In [11]:
df1['category'].nunique()

4

In [12]:
df1['important']

0    y
1    n
2    y
3    n
Name: important, dtype: object

In [ ]:
df1.important

0    y
1    n
2    y
3    n
Name: important, dtype: object

In [ ]:
df1['category'].value_counts()

cat1    1
cat2    1
cat3    1
cat4    1
Name: category, dtype: int64

In [ ]:
df1['sales'].mean()

281.25

In [ ]:
df1['sales'].max()

890

In [ ]:
df1.columns

Index(['customer', 'category', 'important', 'sales'], dtype='object')

In [ ]:
df1

  customer category important  sales
0        A     cat1         y    123
1        B     cat2         n     45
2        C     cat3         y     67
3        D     cat4         n    890

Find out the records/rows which have important as 'y' and sales>100

In [ ]:
df1[(df1['important']=="y") & (df1["sales"]>100)]

  customer category important  sales
0        A     cat1         y    123

Find out records where the category is cat3 or cat4 and the sales is greater than 50

In [14]:
df1[(df1['category']== 'cat3') & (df1['sales']>50)]

  customer category important  sales
2        C     cat3         y     67