In [ ]:
import csv

In [ ]:
with open("/content/births_usa.csv", 'r') as f:
  reader = csv.reader(f)
  # read column names
  cols = next(iter(reader))
  # read rows
  rows = []
  for i in reader:
    rows.append(i)

In [ ]:
print(cols)

['year', 'month', 'date_of_month', 'day_of_week', 'births']

In [ ]:
len(rows)

5479

In [ ]:
# sample 1 row
rows[0]

['2000', '1', '1', '6', '9083']

In [ ]:
months_list = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

In [ ]:
d = dict.fromkeys(months_list, 0)
d

{'April': 0,
 'August': 0,
 'December': 0,
 'February': 0,
 'January': 0,
 'July': 0,
 'June': 0,
 'March': 0,
 'May': 0,
 'November': 0,
 'October': 0,
 'September': 0}

In [ ]:
for row in rows:
  month_idx = int(row[1])
  birth_count = int(row[-1])

  # update in dictionary
  # month starts with 1 and ends with 12
  # but index starts with 0 and ends with 11
  month_name = months_list[month_idx-1]
  d[month_name] += birth_count

In [ ]:
for month in months_list:
  print(month, d[month], sep=" - ")

January - 5072588
February - 4725693
March - 5172961
April - 4960750
May - 5195445
June - 5163360
July - 5450418
August - 5540170
September - 5399592
October - 5302865
November - 5008750
December - 5194432

In [16]:
# write report in a CSV file
write_path = "/content/births_usa.csv"

with open(write_path,'w') as f:
  writer = csv.writer(f)
  # write column names
  writer.writerow(['month', 'total_births'])
  # write data
  for month in months_list:
    writer.writerow([month, d[month]])

In [ ]:
#Q2 Births_USA_2

In [17]:
week_list = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

# create a dictionary of weeks as keys and births as values
d1 = dict.fromkeys(week_list, 0)
d1

{'Friday': 0,
 'Monday': 0,
 'Saturday': 0,
 'Sunday': 0,
 'Thursday': 0,
 'Tuesday': 0,
 'Wednesday': 0}

In [18]:
s=set()
for row in rows:
  s.add(row[-2])

In [19]:
s

{'1', '2', '3', '4', '5', '6', '7'}

In [20]:
# iterate through all the rows in CSV file and manipulate

for row in rows:
  week_idx = int(row[-2])
  birth_count = int(row[-1])

  # update in dictionary
  # week starts with 1 and ends with 7
  # but index starts with 0 and ends with 6
  week_name = week_list[week_idx-1]
  d1[week_name] += birth_count

In [21]:
# print report 
print(*week_list, sep=",")
print(*[d1[week] for week in week_list], sep=",")

Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
9316001,10274874,10109130,10045436,9850199,6704495,5886889

In [23]:
# write in a CSV file

write_path = "/content/births_usa.csv"

with open(write_path,'w') as f:
  writer = csv.writer(f)
  # write column names
  writer.writerow(week_list)
  # write data
  writer.writerow([d1[week] for week in week_list])

QUESTION 3

In [25]:
path = "/content/temperatures.csv"

with open(path, 'r') as f:
  reader = csv.reader(f)
  cols = next(iter(reader))
  rows = []

  for i in reader:
    rows.append(i)

  print(len(rows), len(cols))

365 13

In [26]:
# what columns are there?
cols

['date',
 'actual_mean_temp',
 'actual_min_temp',
 'actual_max_temp',
 'average_min_temp',
 'average_max_temp',
 'record_min_temp',
 'record_max_temp',
 'record_min_temp_year',
 'record_max_temp_year',
 'actual_precipitation',
 'average_precipitation',
 'record_precipitation']

In [27]:
# how a row looks like?
rows[0]

['2014-7-1',
 '70',
 '63',
 '77',
 '63',
 '82',
 '52',
 '107',
 '1886',
 '1985',
 '0',
 '0',
 '0.09']

In [28]:
# we are interested in month, year, actual_min_temp, actual_max_temp
summary = {}

for row in rows:
  date = row[0]
  year,month,day = map(int,date.split("-"))

  actual_min_temp = int(row[2])
  actual_max_temp = int(row[3])

  # add necessary data
  # if year, month pair is new, create a key-value pair
  if (year, month) not in summary:
    summary[(year, month)] = [actual_min_temp, actual_max_temp]    

  else:
    # compare and update
    if actual_min_temp < summary[(year, month)][0]:
      summary[(year, month)][0] = actual_min_temp 

    if actual_max_temp > summary[(year, month)][1]:
      summary[(year, month)][1] = actual_max_temp
    
len(summary)

12

In [31]:
# write in a CSV file
write_path = "/content/temperatures.csv"
with open(write_path, 'w') as f:
  writer = csv.writer(f)

  # write column headers
  new_cols = ["year", "month", "actual_min_temp", "actual_max_temp"]
  writer.writerow(new_cols)
  print(new_cols)
  # write data
  for key,val in sorted(summary.items()): 
    data = [key[0], key[1], val[0], val[1]]
    writer.writerow(data)
    print(data)

['year', 'month', 'actual_min_temp', 'actual_max_temp']
[2014, 7, 62, 92]
[2014, 8, 63, 91]
[2014, 9, 61, 103]
[2014, 10, 59, 98]
[2014, 11, 51, 90]
[2014, 12, 39, 83]
[2015, 1, 37, 85]
[2015, 2, 46, 88]
[2015, 3, 48, 93]
[2015, 4, 49, 92]
[2015, 5, 50, 84]
[2015, 6, 58, 91]