Q-1 What does sequence mean and which three types of data fall into this
category?
ans : sequence is used to stored the different form of data , there are three 
famous sequence **1 list** [] its stored in square bracket and its is a mutable 
2nd **tuples** its stored in {} and it is immutable 
3rd **strings**  its stored in single comma and double comma

Q 2

In [ ]:
l = [1,2,3,4]
l.insert(2,5)
l

[1, 2, 5, 3, 4]

In [ ]:
del l[0]
l

[2, 5, 3, 4]

In [ ]:
l.append(6)
l

[2, 5, 3, 4, 6, 6]

In [ ]:
l.sort()
l

[2, 3, 4, 5, 6, 6]

In [ ]:
l.pop()

6

In [ ]:
l

[2, 3, 4, 5, 6]

In [ ]:
l.reverse()

In [ ]:
l

[6, 5, 4, 3, 2]

In [ ]:
len(l)

5

In [ ]:
l[: : ]

[6, 5, 4, 3, 2]

Q-3 Write a program in Python to remove duplicate items from a list. (10 Marks)
Input: [2,3,4,5,2,6,3,2]
Output: [2,3,4,5,6]

In [ ]:
input = [2,3,4,5,2,6,3,2]
list(set(input))

[2, 3, 4, 5, 6]

Q-4 Check if the given string contains all numeric values if it contains print True otherwise print False using
string operation.(4 Marks)
Example input: ‘’53515’’, ‘’543acd45’’
Output : True , False

In [ ]:
input = "53515","543acd45"
input[0].isnumeric()
input[1].isnumeric()

False

Q-5 Here it is given strings, store the given string into variable and change it into the expected results
performing various string operations and print the result.(10 Marks)
Sample String : 'abc', 'xyz' ,'pQr'
Expected Result : 'ABC_Xyz_pqr

In [ ]:
s = 'abc', 'xyz' ,'pQr'
list(s)[0].upper()

'ABC'

Q-7 find the second occurrence of substring “aba” in the given string “aabaccaabcabaaabac” (5 Marks)

In [ ]:
str ="aabaccaabcabaaabac"
str.find('aba',2)

10

Q-8 Write a Python program to get a string from a given string where all occurrences of its first char have
been changed to '$', except the first char itself. (10 Marks)
Sample String : 'restart'
Expected Result : 'resta$t'

In [ ]:
str = "restart"

Q - 11

In [1]:
tup = ('e', 'x', 'e', 'r', 'c', 'i', 's', 'e', 's')
JOIN(tup)

NameError: ignored

q-10

In [ ]:
tuplex = ("w", 3, "r", "e", "s", "o", "u", "r", "c", "e")
5 in tuplex

False

In [ ]:
## Q12
tuple =  {10, 5, 11, 15, 13,11, 20}
tuple

{5, 10, 11, 13, 15, 20}

In [ ]:
d=